### ISSUE TITLE
Windows build seems to be broken

### ISSUE THREAD

**Issue by bschaatsbergen** [bschaatsbergen/ntest#21]
When running ntest .exe on windows:

```
PS C:\Users\bruno> ntest -a binx.io --headers
time="2021-12-17T16:36:21+01:00" level=fatal msg="socket: The requested protocol has not been configured into the system, or no implementation for it exists."
```

I suspect it's failing on the Ping

**Comment by bschaatsbergen** [comment]
I wonder if we even want/should support windows. Thoughts @tiborhercz ?

**Comment by tiborhercz** [comment]
🤔 good question. I would keep it simple and just support Linux and Mac for now. Later we can always add windows support.

**Comment by bschaatsbergen** [comment]
Closing, won't support Windows.
